name: Android APK Derleme
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gerekli Araclar
        run: |
          pip3 install --user --upgrade buildozer cython
          sudo apt-get install -y libsqlite3-dev gawk unzip zlib1g-dev libffi-dev libssl-dev
      - name: APK Derle
        run: |
          yes | buildozer -v android debug
      - name: APKyi Kaydet
        uses: actions/upload-artifact@v2
        with:
          name: uygulama-paketi
          path: bin/*.apk
